//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.UnitTests.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IXmlPayloadService")]
    public interface IXmlPayloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlPayloadService/GetStatusCodeOfXMLPayload", ReplyAction="http://tempuri.org/IXmlPayloadService/GetStatusCodeOfXMLPayloadResponse")]
        int GetStatusCodeOfXMLPayload(System.Xml.XmlElement xmlElement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlPayloadService/GetStatusCodeOfXMLPayload", ReplyAction="http://tempuri.org/IXmlPayloadService/GetStatusCodeOfXMLPayloadResponse")]
        System.Threading.Tasks.Task<int> GetStatusCodeOfXMLPayloadAsync(System.Xml.XmlElement xmlElement);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXmlPayloadServiceChannel : ABM.UnitTests.WebService.IXmlPayloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlPayloadServiceClient : System.ServiceModel.ClientBase<ABM.UnitTests.WebService.IXmlPayloadService>, ABM.UnitTests.WebService.IXmlPayloadService {
        
        public XmlPayloadServiceClient() {
        }
        
        public XmlPayloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlPayloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlPayloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlPayloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetStatusCodeOfXMLPayload(System.Xml.XmlElement xmlElement) {
            return base.Channel.GetStatusCodeOfXMLPayload(xmlElement);
        }
        
        public System.Threading.Tasks.Task<int> GetStatusCodeOfXMLPayloadAsync(System.Xml.XmlElement xmlElement) {
            return base.Channel.GetStatusCodeOfXMLPayloadAsync(xmlElement);
        }
    }
}
